### PR TITLE
Reformat testdata filepath

### PR DESCRIPTION
**Pull request by wyq977**
* ensure test files are accessiable in other OS
* better logging with Logf
* add sample small video files for ffmpeg
* add example nfo and placeholder for decode test

### CODE REVIEW

**Comment by wyq977** [comment]
Nothing too important in this PR, rn the test files are stil quite messy as I hope to generate mp4/audio on test with ffmpeg but didnt got time to do so. 

* If u run test for ffmpeg, a error is caught for 千与千寻, not sure if its due to my ffmpeg
* tests for notify/imdb will require a config, not sure if copying config.yaml.sample is needed for that

**Comment by allanpk716** [comment]
Some test data is very large, I am still considering whether to use additional projects to store it, otherwise there will be a large number of test files in this project, which will be troublesome to download in the future. The content you submitted is very helpful, may not merge immediately, put it for me as a reminder. thank you

At present, many unit tests in the project write local absolute paths. In order to verify the function quickly and not friendly to others, this will be uniformly dealt with in the New Year.

**Comment by wyq977** [comment]
Yeah, now that I think about the test file adding to codebase git isnt a clever idea. Might lead to large git later on, I will try fix all filepath issue in the branch first and then move to solve the file issue.

For mp4/audio, my sugesstion is choose either of these:

1. Create mp4/audio with desired audio tracks, subtitles with ffmpeg
    * could be done but much more difficult and time consuming just to make video
    * srt text can be generated using random text
2. Make a diff repo for test files
    * ez to implement

But in all cases, a systematic scheme of the test files would be needed.

**Comment by wyq977** [comment]
Hi @allanpk716  这里noraml formatter regex 好像有点问题 我看看这样改行不行 (https://github.com/allanpk716/ChineseSubFinder/pull/142/commits/432810352014f28ff88cbe96a0a2600377e88831)
另外sub_format_changer_test.go 里面 想这些例子，subLang 只会return`简` (expected: `简英`)

主要是因为这个`IsMatchThisFormat `判断 `../../../TestData/sub_format_changer/test/movie_org_emby/AAA/AAA.zh.ass` 会return `subLang = MatchLangChs` 可是 testcase 和想要的结果都是 `简英MatchLangChsEng`, 我改动了一下 test 和 normal.go 没敢变太多 怕牵扯后续调用



IsMatchThisFormat: https://github.com/wyq977/ChineseSubFinder/blob/432810352014f28ff88cbe96a0a2600377e88831/internal/pkg/sub_formatter/normal/normal.go#L34

Test file changed:
https://github.com/wyq977/ChineseSubFinder/blob/432810352014f28ff88cbe96a0a2600377e88831/internal/pkg/sub_formatter/sub_format_changer_test.go#L67

**Comment by wyq977** [comment]
后续我会整理下TestData TestCode 应该只会改 test 除非发现 bug，确保后面能顺利 merge

**Comment by wyq977** [comment]
有一些 test 需要其他配置软件 感觉放到 integration test 比较好emby_api_test

**Comment by allanpk716** [comment]
你先按你的思路来，这两天看连续剧，还发现时间轴矫正有些问题，需要趁着我还记得细节得先处理。

**Comment by wyq977** [comment]
现在internal/pkg/下面的test files 基本都在https://github.com/wyq977/CSFTestFiles

还有几个需要视频文件在考虑上传什么
1.  ffmpeg json 需要对应的视频
    可以考虑 ffmpeg 生成视频 `ffmpeg -y -i in.suffix -filter:v scale=640:360,setsar=1/1 -pix_fmt yuv420p -c:v libx264 -preset:v slow -profile:v baseline -x264opts level=3.0:ref=1 -b:v 700k -r:v 25/1 -force_fps -movflags +faststart -c:a libfaac -b:a 80k -pass x out.mp4
`
2. sub_timeline_fixer （这些好像不能用生成的视频音频 得用real data）
https://github.com/allanpk716/ChineseSubFinder/blob/94a396757333caf6609a076e74fcdebf4fdc82a7/internal/pkg/sub_timeline_fixer/fixer_test.go#L680
https://github.com/allanpk716/ChineseSubFinder/blob/94a396757333caf6609a076e74fcdebf4fdc82a7/internal/pkg/sub_timeline_fixer/restore_test.go#L9
3. vosk_api: need sample audio, dont know what it does
https://github.com/allanpk716/ChineseSubFinder/blob/94a396757333caf6609a076e74fcdebf4fdc82a7/internal/pkg/vosk_api/vosk_client_test.go#L6
4. emby_api: 好像需要emby server？

这几个好像是需要proxy 才能跑？
proxy_helper, rod_helper

这里好像有bug
https://github.com/allanpk716/ChineseSubFinder/blob/94a396757333caf6609a076e74fcdebf4fdc82a7/internal/pkg/sub_helper/sub_helper_test.go#L52

**Comment by allanpk716** [comment]
1. ffmpeg  这块的测试用例我觉得不急，因为一般来说比较稳定，大概率本程序不会改动这个部分了，除非 ffmpeg 更新。
2. sub_timeline_fixer  这个测试用例暂时覆盖字幕校正字幕的比较容易，使用音频校正字幕的功能，也是比较麻烦，主要是体积太大。
3. vosk_api，项目中有很多之前选择实现方案写的测试用例，比如这个，其实是弃用了的，这个是想自建一个本地的翻译服务器。我抽时间清理下这些弃用的测试方案吧，不然修复起来意义不大。
4. emby_api，需要对应的 emby 媒体服务器才方便测试。虽然也可以按 golang 的 mock 来做测试用例，不过我还没实践过···


很多地方有本地的测试引荐的引用，需要我抽时间整理出来。会看看你现在整理的 https://github.com/wyq977/CSFTestFiles 这个项目的存放方式。

**Comment by allanpk716** [comment]
有些关于测试用例的改动，我先以原来的方式解决冲突合并先，确保 v0.19.x 稳定后，再统一处理测试用例相关的问题。到时候需要按你提供的思路也想一下怎么整理便于后续的测试和开发。

**Pull request merged**
